### ISSUE TITLE
Update unit tests for PHP 7.x

### ISSUE THREAD

**Issue by hdp617** [GoogleCloudPlatform/appengine-php-sdk#20]
PHP version: 7.4.11
For example, running phpunit fails with
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function google\appengine\runtime\Glob::doGlob(), 0 passed in /home/huypham/dev/ws/appengine-php-sdk/google/appengine/runtime/GlobTest.php on line 148 and at least 1 expected in /home/huypham/dev/ws/appengine-php-sdk/google/appengine/runtime/Glob.php:51
Stack trace:
#0 /home/huypham/dev/ws/appengine-php-sdk/google/appengine/runtime/GlobTest.php(148): google\appengine\runtime\Glob::doGlob()
#1 [internal function]: google\appengine\runtime\GlobTest->testErrors()
#2 /home/huypham/dev/ws/appengine-php-sdk/vendor/phpunit/phpunit/src/Framework/TestCase.php(865): ReflectionMethod->invokeArgs(Object(google\appengine\runtime\GlobTest), Array)
#3 /home/huypham/dev/ws/appengine-php-sdk/vendor/phpunit/phpunit/src/Framework/TestCase.php(743): PHPUnit_Framework_TestCase->runTest()
#4 /home/huypham/dev/ws/appengine-php-sdk/vendor/phpunit/phpunit/src/Framework/TestResult.php(609): PHPUnit_Framework_TestCase->runBare()
#5 /home/huypham/dev/ws/appengine-php-sdk/vendor/phpunit/p in /home/huypham/dev/ws/appengine-php-sdk/google/appengine/runtime/Glob.php on line 51
```

cc: @hazemm96

**Comment by hdp617** [comment]
Comment out the `testErrors()` function, there are still a couple of errors.
```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-5.5.tar.bz2
0.09s$ curl -sSf --retry 5 -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
curl: (22) The requested URL returned error: 404 Not Found
```
