### ISSUE TITLE
[Question] How to use it for local development environment?

### ISSUE THREAD

**Issue by rulrok** [GoogleCloudPlatform/appengine-php-sdk#3]
I'm trying to use it on my Laravel application where I need to upload large files directly to the bucket storage.

I have this on my code

```php
        $options = ['gs_bucket_name' => env('PANO_IMAGES_BUCKET_NAME')];
        $upload_url = CloudStorageTools::createUploadUrl('/upload', $options);
```

But the local server times out and I have this stack trace on my log:

```php

[2015-09-10 19:31:45] local.ERROR: exception 'google\appengine\runtime\RPCFailedError' with message 'Remote implementation for blobstore.CreateUploadURL failed' in /home/vagrant/pano-cms/vendor/google/appengine-php-sdk/google/appengine/runtime/VmApiProxy.php:179
Stack trace:
#0 /home/vagrant/pano-cms/vendor/google/appengine-php-sdk/google/appengine/runtime/ApiProxy.php(40): google\appengine\runtime\VmApiProxy->makeSyncCall('blobstore', 'CreateUploadURL', Object(google\appengine\CreateUploadURLRequest), Object(google\appengine\CreateUploadURLResponse), NULL)
#1 /home/vagrant/pano-cms/vendor/google/appengine-php-sdk/google/appengine/api/cloud_storage/CloudStorageTools.php(244): google\appengine\runtime\ApiProxy::makeSyncCall('blobstore', 'CreateUploadURL', Object(google\appengine\CreateUploadURLRequest), Object(google\appengine\CreateUploadURLResponse))
#2 /home/vagrant/pano-cms/app/Http/Controllers/Web/PanoController.php(54): google\appengine\api\cloud_storage\CloudStorageTools::createUploadUrl('/upload', Array)
#3 [internal function]: App\Http\Controllers\Web\PanoController->create()
#4 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#5 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('create', Array)
#6 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Web\PanoController), Object(Illuminate\Routing\Route), 'create')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /home/vagrant/pano-cms/app/Http/Middleware/Authenticate.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Web\PanoController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'create')
#15 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'create')
#16 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#17 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#24 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /home/vagrant/pano-cms/app/Http/Middleware/VerifyCsrfToken.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /home/vagrant/pano-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /home/vagrant/pano-cms/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 {main}  
```

I was already expecting it to not work locally, but can I set some setting so it will not try to actually do something when in local develop environment and time out my application?

I want to write my code as seamlessly as possible. I do not want to have to protected my code with some clunky if statement for verifying my actual environment.

**Comment by sjlangley** [comment]
You need to be running your tests in the App Engine development environment, which provides a local simulation of all app engine services [https://cloud.google.com/appengine/docs/php/tools/devserver]

**Comment by rulrok** [comment]
Thank you. That solved my problem. I didn't know about that.

**Comment by sweiguny** [comment]
what if i dont use standard environment but flexible environment?
